# Generated by Django 5.0.14 on 2026-10-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('monitor_type', models.CharField(default='HTTP', max_length=50)),
                ('check_interval', models.IntegerField(default=5, help_text='Check interval in minutes')),
                ('timeout', models.IntegerField(default=10, help_text='Timeout in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('WARNING', 'WARNING'), ('PAUSED', 'PAUSED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=20)),
                ('reason', models.TextField()),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Downtime duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('WARNING', 'WARNING')], max_length=20)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.IntegerField(default=0, help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True, default='')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
